version: '3'

services:
  database:
    build:
      context: ./database
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./database/data:/var/lib/mysql

  php-fpm:
    build:
      context: ./api
    depends_on:
      - database
    environment:
      - DATABASE_URL=mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@database:3306/${DATABASE_NAME}?serverVersion=5.7
    volumes:
      - ./api:/var/www

  nginx:
    image: openresty/openresty:alpine
    volumes:
      - ./api:/var/www
      - ./nginx/sites/default.conf:/etc/nginx/conf.d/default.conf
      - ./logs:/var/log
    depends_on:
      - php-fpm
    ports:
      - "8080:80"


